### ISSUE TITLE
Mis-represented spyrmsd performance?

### ISSUE THREAD

**Issue by RMeli** [JerryJohnsonLee/CanonizedRMSD#8]
Hello. I've just seen your pre-print about this work, and the comparison with [spyrmsd](https://github.com/RMeli/spyrmsd) performance caught my eyes (I'm the author of [spyrmsd](https://github.com/RMeli/spyrmsd)). Could you please clarify which backend did you use? I was unable to find it in your manuscript.

In our original published work, [spyrmsd](https://github.com/RMeli/spyrmsd) could use either the [networkx](https://networkx.org) or [graph-tool](https://graph-tool.skewed.de) backends. The former is the default (since it's widely available), but it's known to be slow.

Since version `0.7.0` of [spyrmsd](https://github.com/RMeli/spyrmsd), released the 5th of April 2024, [rustworkx](https://www.rustworkx.org) is also supported, which is both fast and widely available.

 [rustworkx](https://www.rustworkx.org) or [graph-tool](https://graph-tool.skewed.de) are the backends to be used for a fair comparison and benchmarks.

---

These are the timings I get running with the [rustworkx](https://www.rustworkx.org) and [graph-tool](https://graph-tool.skewed.de) backends for the molecules in `testsets` (Table 1 in your manuscript) on a Apple M1 Pro:

| System | `spyrmsd` [rustworkx] (s) | `spyrmsd` [graph-tool] (s) | `CanonizedRMSD.py` (s) |
|---|-------|-------|-------|
| a | 0.309 | 0.266 | 0.230 |
| b | 0.305 | 0.257 | 0.260 |
| c | 0.307 | 0.250 | 0.402 |
| d | * | * | * |
| e | 6.617 | 1.698 | 307.3 |

These are much faster than the ones you reported in your manuscript. For a fair comparison, I also run the test cases on the Apple M1 Pro with `CanonizedRMSD.py` (same Python environment used for the [spyrmsd](https://github.com/RMeli/spyrmsd) timings). 

Therefore, it seems that with the high-performant backends ([rustworkx](https://www.rustworkx.org) and [graph-tool](https://graph-tool.skewed.de)), [spyrmsd](https://github.com/RMeli/spyrmsd) is much faster than claimed in your pre-print, and performs significantly faster than `CanonizedRMSD.py` (2 or 7 seconds instead of 5 minutes). 

I'm not sure why the timing for `e` is not reported for [spyrmsd](https://github.com/RMeli/spyrmsd) in your Table 1.

---

I was unable to run test `d` with [spyrmsd](https://github.com/RMeli/spyrmsd) because I hit the following:
```
[21:43:36] Explicit valence for atom # 0 N, 4, is greater than permitted
[21:43:36] ERROR: Could not sanitize molecule ending on line 446
[21:43:36] ERROR: Explicit valence for atom # 0 N, 4, is greater than permitted
[21:43:36] Explicit valence for atom # 0 N, 4, is greater than permitted
[21:43:36] ERROR: Could not sanitize molecule ending on line 446
[21:43:36] ERROR: Explicit valence for atom # 0 N, 4, is greater than permitted
```

Given the size of the molecule (217 atoms) I haven't checked where this is coming from, but the error would indicate an issue with your input file.

Interestingly, I also get the same exception using `CanonizeRMSD.py`:

```
rdkit.Chem.rdchem.AtomValenceException: Explicit valence for atom # 0 N, 4, is greater than permitted
```

Therefore, I'm not entirely sure if the molecule `d` available in the repository is the same used for benchmarks.

---

If you only used the [networkx](https://networkx.org), I would kindly ask to update your pre-print with the correct timings for [spyrmsd](https://github.com/RMeli/spyrmsd) using the [graph-tool](https://graph-tool.skewed.de) and/or [rustworkx](https://www.rustworkx.org), especially Table 1, Figure 7, and Figure 8.

I'd be happy to provide any assistance, and I'll make [rustworkx](https://www.rustworkx.org) the default backend in future releases, give the potentials for misrepresentation of performance when using the current default [networkx](https://networkx.org).

**Comment by JerryJohnsonLee** [comment]
Hello @RMeli, thanks for checking these numbers. We will run spyrmsd again to confirm the performance and make any necessary changes in our manuscript.

**Comment by RMeli** [comment]
Hello @JerryJohnsonLee, do you have the inputs for n-alkanes (Fig. 7) and water clusters (Fig. 8) so that I can run some benchmarks? Thank you.

**Comment by JerryJohnsonLee** [comment]
Hi @RMeli, the n-alkane and water cluster molecules have been updated to the main branch under `testsets`.

**Comment by JerryJohnsonLee** [comment]
Hi @RMeli I have tried running spyrmsd on my local computer (single core with Intel Core i7 11375H) and get numbers similar to what we reported in the original paper (for spyrmsd we were using the networkx backend). By using the rustworkx backend, the performance with spyrmsd has indeed improved but still slower than our CanonizedRMSD algorithm, even though our code is based on a fully python implementation (on this aspect it is fairer to compare performance with the networkx backend). Please be aware that we do experiments on the structures with all hydrogens retained. For running spyrmsd, we are using the following command:
`python -m spyrmsd 1.sdf 2.sdf -m -g [rustworkx/networkx] --hydrogen`. Please let me know if I am using the wrong command.

Regarding molecule d, I could correctly obtain results using our code but got the same error as you mentioned with spyrmsd. Please see screenshot below:
![image](https://github.com/JerryJohnsonLee/CanonizedRMSD/assets/16594872/c5ac14e2-e1a8-4b15-b469-a0a171c4f351)

Here is a summary of the timings I got for running the benchmarks again on my local machine (mean and standard deviations based on 10 independent runs)

|System|`spyrmsd` [rustworkx] (s)|`spyrmsd` [networkx] (s)|`CanonizedRMSD.py` (s)|
|---|---|---|---|
|a|0.27 ± 0.02|0.49 ± 0.03|0.38 ± 0.02 |
|b|0.6 ± 0.1|1.16 ± 0.05|0.48 ± 0.08|
|c|6.97 ± 0.31|22.87 ± 0.99|0.67 ± 0.03|
|d|**Error**|**Error**|8.73 ± 0.20 |
|e|**Killed**|**Killed**|336 ± 1.9|

**Comment by RMeli** [comment]
Hi @JerryJohnsonLee, thank you for double checking and the additional details.

> Please be aware that we do experiments on the structures with all hydrogens retained.

Ah! I missed that CanonizedRMSD keeps the hydrogen by default. This is very uncommon in real applications, and all major RMSD tools I'm aware of remove/ignore them. This would explain the difference in the benchmarks. I would expect CanonizedRMSD to become faster than `spyrmsd` at some point, but the crossover was way too early compared to what I observed while using `spyrmsd` extensively. However, I always removed the hydrogen atoms in my applications, and keeping hydrogen atoms quickly increases the computational complexity.

By keeping the hydrogen atoms I get timings similar to what you report, so mystery solved! =)

I think it would be good to clarify this (IMO uncommon) choice in the paper, to make it clearer to the reader what is going on (and why graph isomorphism deteriorates so quickly). Even better, it would be interesting to show both (with and without hydrogen).

> Regarding molecule d, I could correctly obtain results using our code but got the same error as you mentioned with spyrmsd.

This is odd. For me, both fail. I'm using the same version of RDKit `2024.03.3`. I'm not sure why for you only `spyrmsd` fails.

> on this aspect it is fairer to compare performance with the networkx backend

As a side note, I'd tend to disagree with this statement. I think if you compare for speed, then it is fairer to compare with the best possible available implementation.

**Comment by RMeli** [comment]
FYI

![Screenshot from 2024-06-28 22-02-32](https://github.com/JerryJohnsonLee/CanonizedRMSD/assets/11348981/3bd19511-17be-469c-8d80-906df8050032)

**Comment by JerryJohnsonLee** [comment]
Hi @RMeli I have recently done some code restructures and you could try the latest code on master branch. You could install using `pip install .` and then `rmsd d/1.sdf d/2.sdf`. BTW I have tried two environments with rdkit 2022.03.3 and 2023.09.5 and they both work. I did not try the 2024.03.3 version.

Thank you for your suggestion on making some contents clearer, and I will definitely incorporate them in the next version of the manuscript.

**Comment by RMeli** [comment]
My test yesterday was with a fresh clone of the repository. It might be down to a different environment.
